---
abstract: 'Turn “unicode” and “byte” string text into lines of a given width, soft-hyphenating broken words'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Fold
no_index:
  directory:
    - t
    - inc
requires:
  String::UnicodeUTF8: 0
  Test::More: 0
version: 0.5
